# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.provision "shell" do |s|
        s.path = "foxpass_setup.py"
        s.args = "--base-dn dc=example,dc=com --bind-user binder --bind-pw BIND_PW_HERE --api-key API_KEY_HERE"
    end
end
